language: generic
sudo: false
cache:
  directories:
  - "$HOME/.stack/"
branches:
  only:
  - source
env:
  global:
  - GH_NAME="thayumanavarhsv2017"
  - secure: CLiUiADescY8U5s6VZ/32nup7twBUVGmX/gLWwqFiZkjh21QdZkc3Pe9Otq0Ig0eljxlOJI/ivDl4rywyuA3Ykm0IlMGG9nvAhKbIcqt7ZujVQ2yaPy19QscKEp5AdscQ6mrT6Ew986KADOwz+53br5soi65hn9RniRIJ1wstlrn2enHlu/5b5Zk47cKKayRwTH9wvwyps/NUmvpKjtHnjH1iFkwdBU/REXg8mvSfhuQxnAM+R7AjtPUCPrOXi3An4J3r0mHk0JeG5I1IbYEyNHKuKFK2E8r4kPCzRDK/aYs13sOA7xWyS0pfEhZ4n6MjRwwOPdSJimlMReI+JPy/Dx0WwnbcfpEarw74J02DMR/jVSPwxt0jeCe8C6+txfvoipkY5PGLodMvyBHaq8XIHyii6dC7XrbfeHLuRJhvHV08Jw5ltUmhqZYXdSjgO71W3uBy0RyaBxnYsqeaVwd1YrQE0hgnUZj4D8ezJQ+n1hVpHK7beoVA4L0lD+KGu66ALN22Ly+tGHH3cZW9GCslcXtV8EzBJ5WuaAs/Ecya5SDRUZSDJtKlL1WTKwJHcjlnPyqKnY2JBgMk2IbBd+gYWbabeA4hAGCizyS59d17L8qzykQIHfWNC524mnSTRh7WUvJaoOa/CP929UlONRrll4suI3l0R1Wu1cX5Qxnb6U=
before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz
  | gunzip > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack
- export PATH=~/.stack/programs/x86_64-linux/ghc-7.10.2/bin:$PATH
- git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README
  | grep -v CNAME | xargs -r git rm'
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
install:
- stack setup --no-terminal --skip-ghc-check
- stack build --only-snapshot --no-terminal
before_script:
- git config --global user.name "thayumanavarhsv201"
- git config --global user.email "valambals@gmail.com"
script:
- stack build --no-terminal
- stack ghc site.hs
- "./site build"
after_script:
- cd _site
- export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
- git init
- git config --global user.email "valambals@gmail.com"
- git config --global user.name "thayumanavarhsv2107"
- git remote add github https://${GH_TOKEN}@${REMOTE}
- git add --all
- git ls-files
- git status
- git commit -m "Built by Travis (build $TRAVIS_BUILD_NUMBER)"
- git push --force --quiet github master:master
notifications:
  email: false
